import { LibraryItem } from './types';

// Helper to generate consistent layouts, but we will define specific blocks for each item below.
// This function is kept for fallback but mostly unused in the new data structure.
const genContent = (title: string, type: string) => [
  { type: 'p' as const, content: `${type}: ${title}` }
];

// --- Pre-generated Audio Data ---
// This simulates having real, pre-generated audio files for each article.
// The audio below was generated using the Gemini TTS API for one article's summary.
// For this demo, we reuse the same clip for all articles to prove the concept.
const PRE_GENERATED_AUDIO_EN = "UklGRvxECQBXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YTpECQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA_";
const PRE_GENERATED_AUDIO_CN = "UklGRqJHCQBXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YXiJHCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-i8d1LqSyr6/sv9yvbC5bbrQvdm4cLlYuda4mLhguUq44Lf8t3y3Arf3twW34rcftve3CLcGtwW28ra1tpu2rLactaS0lLSUtCC0mLQctCG0BbQEtACz97M8s++z/LPysv6y8bLgsvmy37Ldsuey6LLHsk+yLLIKsg+y/7EUsg6x/7Cosf+x/rH6sfix7bHuseGx3bHcsdaxzrHascyxx7G/sbOxrLGpsaWxpLGcsZ2xmbGUsaixlLGQsYSwkrCcsIiwg7B7sH+wf7B9sHywe7B3sHWwdLBvsG2wZ7BksGOwYrBfsF2wX7BRsEewP7A/sD6wPbA5sDSwL7AtsCewIbAPr/+v/6/6r/ev+q/1r/iv9a/3L/av9q/0r/Sv9K/z7/Lv8u/yr/Gv8W/wL/Cv8C/wr/8v/q/+r/7v/y/+L/5v/m/+X/3f/e/97/2P/c/9j/1v/V/9T/0f/T/9D/zv/O/83/yv/L/8r/x//H/8b/wf/A/7//vf+9/7v/uv+5/7f/t/+3/7L/sv+x/7H/sP+w/6//r/+r/6f/p/+f/5v/n/+X/5f/lf+P/4v/iv+H/4f/gf+A/3//e/97/3f/c/9z/2f/Z/9f/1//W/9T/0//T/9H/0P/P/87/zv/M/8v/y//K/8j/yP/H/8f/xv/G/8L/wv/A/8H/v/+9/77/uv+6/7f/tv+z/7L/sf+v/6//qP+l/6T/ov+g/5//mv+Z/5b/lP+S/5H/j/+O/47/iP+I/4f/hf+B/3//fP98/3j/eP91/3T/cv9v/2v/av9n/2X/Yv9g/17/Wf9Z/1X/U/9Q/0v/Sf9G/0T/Qf9A/z//Ov85/zX/Nf8y/yz/LP8q/yj/J/8m/yX/Iv8h/yH/H/8d/xz/G/8a/xb/Ff8S/xH/EP8O/w7/Df8M/wn/CP8G/wX/Af8A/73/uv+5/7L/r/+r/6X/o/+d/5j/lP+Q/43/iP+D/37/dP9y/2v/Zf9d/1f/T/9J/0P/Pv83/zD/Kf8l/yH/Gv8T/w3/B/77/t/+x/6n/n/+T/4r/fv9v/1X/RP8y/yX+8/6r/lv+E/2f/Qv8n/u/+Ef1H+qf1D9W/x38QPr29fr1//bC9vr29/YE+Aj4BfsI+gr7DPsJ+vr5CPoH+gP6BPkA+QX5EvkV+Rr5GPkY+R/5N/k2+Tn5OvlC+UL5QvmA+YD5ePl5+Xr5ivmL+Y75nvmh+Z/5pPmj+af5s/m0+br5vvq++sL6w/rH+s/62fra+t365frn+un68vr0+vf6A/sI+wz7Efsc+yP7Jvsm+yn7M/s1+zb7PPtC+0T7SvtO+1P7Yfth+2j7c/t4+378APwE/AX8DvwQ/BH8Jvwq/Cz8NPw5/D/8SvzU/Nn81vzL/Mr8x/x//Hz8e/x7/HX8cPxr/Gr8Zvxi/GH8XfxT/FL8SfxJ/EX8Pvw8/Dr8O/w3/DD8LPwo/CT8Ifwh/B38Hfwd/Bv8GvwV/BP8FvwQ/An8BPwB/AD8APz9+/j79fv4+/j78Pvq++n75fvj++X74Pvf+9z73fvf+9r72/va+9f71vvQ+8/7zvzK/Mj8yPzI/Mn80/zW/Nj82vzj/On87vz3/gICBAQIChIKFAoYCiwKNgpECkgKTApQCloKXApkCm4KiAqOCpQKoAq+CsoKzQrcCuwK7gr2CvoK/AsOCxQLGAseCyMLKQsrCzQLOAs/C0kLTQtTC1kLYgtnC30LgwudC6MLqQu4C74L0wvTC+AL+wv/DAkMEwwVDBkMJQwmDCoMLQwzDDkMRQxLDFIMVAxYDGIMZwxyDH4MhAyMDJoMpgzGDM4M9g0CDQoNHg0qDTANGg0gDSENIQ0dDSENIA0bDSMNJA0kDSENIQ0hDSENHA0eDSEMIwwhDCMNJw0iDSMNJg0fDSELIQwhDCMNIw0jDSMNIw0iDSMNIwwfDSELIQwhDCMNIQ0jDSMNIQ0hDSMNIA0eDSENIwwhDCMNIw0kDSMNIQ0gDSINHQ0jDCMNIQ0jDSMNJg0hDSEMIg0jDSMNIg0hDCMNIQ0hDCMNIQ0jDSEMIQ0jDSMMIg0hDSINHA0hDSMNIA0jDSMNIQ0hDCMNIQ0hDSMNIA0gDSENIw0hDSMNIw0hDSENIw0jDSENIw0jDSMNIQ0hDSENIw0hDSMMIQ0hDCMNIg0hDCMNIQ0jDSEMIw0hDCMNIQ0hDCMNIg0jDCMNIQ0jDSMNIQ0hDSENIw0jDSMNIQ0hDSEMIQ0hDSMNIA0jDSMMIQ0jDCMNIQ0jDSMNIw0hDSMNIA0hDSMNIg0jDCMNIQ0hDCMNIw0jDCMNIw0hDSEMIQ0jDCMNIw0jDSEMIQ0hDCMNIg0jDSMMIQ0jDCMNIg0jDSENIw0hDSENIQ0hDSEMIQ0jDCMNIg0jDSENIQ0hDCMNIg0jDSENIQ0jDSENIQ0jDSEMIQ0hDSMNIA0jDSMMIQ0jDCMNIQ0jDSMNIQ0hDCMNIg0hDSENIw0jDSEMIQ0hDCMNIg0jDCMNIw0hDSENIw0jDSENIw0jDSENIw0jDSMNIQ0jDSENIQ0hDSMNIQ0jDSMNIA0jDCMNIQ0jDSMNIQ0hDCMNIg0jDCMNIQ0jDSMNIQ0hDSMNIQ0hDSEMIQ0jDCMNIg0jDCMNIw0jDSENIQ0jDSENIQ0jDSENIQ0jDSENIA0jDCMNIQ0jDSMNIQ0hDSMNIQ0hDCMNIg0jDCMNIQ0hDSMMIQ0hDCMNIg0hDSENIA0jDSMMIA0hDSEMIQ0jDSMNIA0hDCMNIQ0hDCMNIg0jDSEMIQ0jDCMNIw0jDSENIQ0hDCMNIg0jDCMNIQ0jDCMNIw0jDSMNIw0jDSENIw0hDSENIQ0hDCMNIw0jDSENIA0jDSMNIw0jDCMNIg0jDSEMIQ0jDCMNIw0jDSEMIQ0hDCMNIg0jDSENIQ0jDSEMIQ0jDCMNIg0hDSEMIQ0jDCMNIw0jDSENIw0hDSENIw0hDCMNIQ0hDCMNIg0jDSMNIw0jDSENIQ0jDSMNIQ0jDSENIQ0jDCMNIQ0jDSEMIQ0jDCMNIQ0jDSMNIQ0jDCMNIg0jDSENIw0jDSENIQ0hDCMNIQ0hDCMNIw0jDSMNIQ0hDCMNIw0jDSEMIQ0jDCMNIg0hDCMNIg0jDSEMIQ0jDCMNIQ0jDSEMIQ0hDCMNIg0jDCMNIg0jDSENIQ0hDSENIw0hDSEMIw0hDSEMIQ0jDCMNIw0hDSEMIQ0jDSMNIA0jDSMMIQ0jDCMNIQ0jDSMNIQ0hDCMNIg0jDSMMIQ0jDCMNIg0jDSENIA0jDSMMIQ0hDSENIQ0hDSEMIQ0jDSMNIQ0jDSMMIQ0jDCMNIQ0jDSMNIQ0hDSENIQ0hDSMMIQ0jDSMNIQ0jDSMMIA0jDSIMIQ0jDSMNIQ0hDSENIQ0jDSMNIw0jDSENIQ0hDSMNIQ0hDSMMIQ0jDSMMIQ0hDSENIQ0jDSMNIQ0jDSMNIQ0hDSENIQ0hDSMNIA0jDSMMIQ0hDSENIQ0jDSMNIQ0hDSMMIQ0jDSMNIQ0hDSMNIA0jDSMMIQ0hDSMNIA0jDSMMIQ0hDSMNIQ0hDSMNIA0hDSMNIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMNIQ0hDSMNIQ0hDSMNIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIQ0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0hDSMMIA0h-";

const addAudioData = (item: LibraryItem): LibraryItem => ({
  ...item,
  audioData: {
    en: PRE_GENERATED_AUDIO_EN,
    cn: PRE_GENERATED_AUDIO_CN,
  }
});


// --- CN Data (Based on PDF) ---

const casesCnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'manufacturing-innovation-radar', 
    type: 'case', 
    title: "构建“创新雷达”：将概念迭代周期缩短至数小时", 
    subtitle: "协助头部制造业利用 AI Agent 构建系统化的信息雷达，解决研发初期的信息过载难题，成功将概念迭代周期从数周缩短至数小时。", 
    updatedAt: "2026-03-01", 
    readTime: "8", 
    tags: ["制造", "产品创新"], 
    clientIntro: "某头部制造业公司。", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cUN0.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "“第一天难题”：淹没在数据中，却渴望洞察" },
      { type: 'p', content: "许多企业面临的问题是产品创新的‘第一步’最难迈出。该公司的产品经理每天被数百篇行业报告、竞品动态和技术论文淹没。传统的创新流程始于一场艰苦的信息消耗战——团队花费数周时间搜集、阅读、试图从碎片中拼凑出趋势。结果往往是灵感枯竭，方向模糊，错过窗口。" },
      { type: 'p', content: "这种被动的、劳动密集型的方法不仅消耗了团队宝贵的精力，更直接导致了高昂的“机会成本”。由于无法快速验证早期概念，多个项目并行推进，最终因市场不匹配而失败，造成了数百万美元的沉没成本，并使公司在激烈的市场竞争中逐渐失去先发优势。" },
      { type: 'h2', content: "解决方案：从“人工搜索”到 AI 驱动的“创新雷达”" },
      { type: 'p', content: "我们没有选择给企业一个单纯的信息工具，而是重新定义了创新的前端流程。我们设计的解决方案分为两个核心部分：一个 7x24 小时运行的 AI 信号情报引擎，以及一个每周进行的人机协作产品概念工作坊。" },
      { type: 'h3', content: "第一步：构建全天候信号情报引擎" },
      { type: 'p', content: "我们与客户的核心研发团队合作，首先定义了四个核心观测维度：前沿技术（学术论文、专利申请）、竞品动态（产品发布、价格调整）、用户反馈（社交媒体、论坛讨论）和供应链信号（新材料、成本波动）。随后，我们部署并训练了专属的 AI Agent，它们自动在这些领域抓取、清洗、交叉验证信息，并将原始数据转化为结构化的洞察。" },
      { type: 'h3', content: "第二步：人机协作概念工作坊" },
      { type: 'p', content: "每周，AI 会基于一周的信号分析，自动生成一份《机会报告》，以摘要形式指出高潜力信号（例如，“AVC 编码模型在汽车座舱娱乐系统中的应用正在升温”）。我们引导产品团队围绕这些高度浓缩的信号进行深度讨论，而 AI 则作为“与会者”同步在场，根据团队的讨论方向实时生成概念草图、用户故事和初步的可行性分析。" },
      { type: 'quote', content: "传统流程是“人海搜寻+头脑风暴”，而 AI 的工作流应该是“系统扫描信息+人机共创产品概念”。" },
      { type: 'h2', content: "成果：速度、节约与全新的研发文化" },
      { type: 'p', content: "通过将繁琐的信息搜集与整理工作完全自动化，产品团队的精力被解放出来，得以专注于最具价值的创造性与战略性思考。AI 提供的不是零散的数据，而是经过预处理的、激发思考的“燃料”，这使得每周的工作坊都能产出高质量的产品概念。最终，公司不仅在财务上获得了显著回报，更重要的是建立了一种全新的、由数据和 AI 驱动的敏捷研发文化。" },
      { type: 'metrics', items: [{ label: '研发时间节省', value: '70%' }, { label: '单品类节省', value: '数百万', sub: '研发费用' }, { label: '迭代周期', value: '数小时', sub: '从数周缩短' }] }
    ] 
  },
  { 
    slug: 'pharma-knowledge-management', 
    type: 'case', 
    title: "解锁“暗知识”：让企业知识库真正实现对话式调用", 
    subtitle: "通过构建企业级知识图谱，将静态的文档库转化为可对话的“企业大脑”，帮助分析师将跨系统的决策响应速度从天级提升至分钟级。", 
    updatedAt: "2026-02-28", 
    readTime: "7", 
    tags: ["医药", "知识管理"], 
    clientIntro: "某头部医药企业。", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cZUF.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "痛点：价值连城却无法使用的宝藏" },
      { type: 'p', content: "每个企业都藏着“暗知识”(Dark Knowledge)，它们散落在项目报告、专家经验、会议纪要和邮件沟通中。该医药企业的市场分析师每月需要分析全国数百家连锁药店的销售数据，并结合内部的营销活动报告，这项工作需耗时超过600小时，从十几个独立的系统中手动提取、清洗和整合数据。新人上手周期长达数月，而核心专家的离职则意味着宝贵经验的永久流失。" },
      { type: 'h2', content: "解决方案：构建企业级 AI 知识图谱" },
      { type: 'p', content: "传统知识管理是“建仓库”，它将文件归档，但知识之间的关联却被割裂，最终建成一座难以导航的迷宫。我们的 AI 知识管理咨询逻辑是“建大脑”。我们首先进行了全面的知识资产战略审计，识别出高价值的知识领域，并设计了一套“知识运营”流程，确保新的知识能够持续地被捕获和更新。" },
      { type: 'p', content: "项目的关键步骤不是简单地导入数据，而是重新设计知识的流动方式。我们利用自然语言处理（NLP）技术，从非结构化的文档中自动提取实体（如药品名称、成分、促销活动）和关系，构建了一个动态的知识图谱。现在，企业管理者只需用自然语言提问：“请对比华南与华东地区，近两年我们A产品在KA渠道的促销投入与销售额的关联度，并分析主要竞品的应对策略。”1分钟内，系统就能生成一份带可视化图表和引用来源的分析报告。" },
      { type: 'h2', content: "影响：从“数据考古”到“实时决策”"},
      { type: 'p', content: "这一变革将分析师的角色从“数据考古学家”转变为真正的“战略顾问”。他们不再需要将时间浪费在重复性的数据提取上，而是可以利用AI提供的深度洞察，为业务部门提供更具前瞻性的建议。企业的决策不再仅仅依赖于少数专家的个人经验，而是建立在可追溯、可验证的集体智慧之上。" },
      { type: 'metrics', items: [{ label: '节省工时', value: '600h+', sub: '每月' }, { label: '决策响应', value: '分钟级', sub: '从天级提升' }] }
    ] 
  },
  { 
    slug: 'fmcg-consumer-insight', 
    type: 'case', 
    title: "告别静态问卷：利用合成用户实现实时市场洞察", 
    subtitle: "利用合成用户技术取代传统问卷，通过 Proactive Agent 进行海量并发访谈，为百亿级单品提供实时的动态市场洞察。", 
    updatedAt: "2026-02-25", 
    readTime: "9", 
    tags: ["快消", "消费者洞察"], 
    clientIntro: "某头部消费品企业。", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1crep.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "痛点：昂贵且过时的“静态照片”" },
      { type: 'p', content: "传统消费者调研如同给瞬息万变的市场拍一张静态照片：它耗资巨大、历时数月，并且结论完全依赖于有限的样本。当最终报告完成时，消费者的偏好可能已经发生了改变。企业面临的困境是，他们基于一张模糊且可能已经过时的照片来决定一个价值数十亿美元的产品的未来方向，这其中充满了风险与不确定性。" },
      { type: 'h2', content: "解决方案：从“拍照”变为“直播”，与市场实时互动" },
      { type: 'p', content: "我们的方法论核心是从“静态洞察”转向“动态感知”。我们利用 Atypica™ 技术，结合客户的一方数据和公开市场数据，生成了数千个与真实消费者画像高度一致的多维虚拟用户。这些“合成用户”不仅有人口统计学特征，更被赋予了价值观、消费习惯和动机模型。" },
      { type: 'p', content: "我们的 AI 咨询团队首先进行了“商业问题解构”，将客户模糊的业务目标（如“提升Z世代用户的购买意愿”）拆解为一系列可被AI探查的核心问题，覆盖用户动机、使用场景、支付意愿等多个维度。随后，Proactive Agent 接管了调研的执行层，它能够模拟一个专业的访谈者，与成百上千的合成用户及真实用户样本同时进行深度、开放式的对话，并根据回答实时追问，挖掘深层原因。我们的分析师则从 AI 提炼的结构化数据中，为客户解读出“健康升级而非功能替代”这样的核心战略机会点，并提供具体的产品功能与营销建议。" },
      { type: 'h2', content: "商业价值：在不确定性中找到确定性"},
      { type: 'p', content: "这种“直播”模式让企业得以在产品概念阶段就进行大规模、低成本的快速试错。他们可以在几天内测试数十种不同的产品概念或营销话术，并获得即时反馈，从而在早期就淘汰掉没有潜力的方案，将资源集中在最有可能成功的方向上。这不仅极大地降低了创新成本，更重要的是，它为企业在快速变化的市场中提供了一种寻找确定性的强大能力。" },
      { type: 'metrics', items: [{ label: '成本降低', value: '60%', sub: '对比传统调研' }, { label: '新品速度', value: '350%', sub: '提升率' }, { label: '洞察速度', value: '100x', sub: '并发处理' }] }
    ] 
  },
  { 
    slug: 'alcohol-channel-growth', 
    type: 'case', 
    title: "千亿级销售网络重塑：实现“创作-分发-激励”闭环", 
    subtitle: "为数千名经销商部署 AI 内容引擎，建立“创作-分发-激励”的自动化闭环，有效解决了渠道内容质量参差-齐与管理困难的问题。", 
    updatedAt: "2026-02-20", 
    readTime: "8", 
    tags: ["酒业", "渠道增长"], 
    clientIntro: "某白酒龙头企业。", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cju9.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "痛点：渠道数字化中的“大水漫灌”" },
      { type: 'p', content: "在新媒体时代，终端门店和关键意见消费者（KOC）的社交影响力对品牌至关重要。但该品牌面临巨大挑战：全国数千家经销商普遍不擅长内容创作，导致社交媒体上的品牌形象质量粗糙、信息不一。总部无法对这些分散的产出进行有效的批量管理和激励。传统的“下达任务+微信群扩散”模式效率极低，内容效果数据由于平台分散如同一个无法追踪的黑洞。" },
      { type: 'h2', content: "解决方案：以内容驱动的 AI 智能工作流" },
      { type: 'p', content: "我们没有仅仅提供一个内容生产工具，而是设计了一套端到端的智能工作流，将“创作-分发-激励”完全打通。首先，我们将品牌的营销诉求（如高端宴请场景、传统佳节送礼）转化为 AI 可理解的创作指令和视觉维度（如画面质感、文化元素、文案风格）。" },
      { type: 'p', content: "在新的工作流中，总部在平台上发布营销任务，经销商只需一键接入 AI 创作助手，输入简单的想法或关键词，即可在数秒内生成符合品牌调性的高质量图文或短视频脚本。内容在发布前会经过 AI 的初步合规性筛选，确保品牌信息准确无误。发布后，平台通过 API 实时追踪内容的传播数据，并根据预设的激励规则（如曝光量、互动率），自动为经销商分配奖励。在这个流程中，AI 同时扮演了创意生产者、质量守门员和效果分析师三个角色。" },
      { type: 'h2', content: "业务影响：将渠道网络转化为品牌放大器"},
      { type: 'p', content: "该方案不仅解决了内容生产的效率和质量问题，更重要的是，它将庞大而松散的经销商网络，转化为了一个高效、可控、数据驱动的品牌内容放大器。总部第一次能够清晰地看到每个区域、每家门店的内容营销表现，并以此为依据优化渠道策略和资源分配。这不仅是一次 IT 系统的升级，更是对传统渠道管理模式的一次根本性重塑。" },
      { type: 'metrics', items: [{ label: '运营效率', value: '+75%' }, { label: '曝光量', value: '5000w+', sub: '深度绑定门店' }] }
    ] 
  },
  { 
    slug: 'real-estate-localization', 
    type: 'case', 
    title: "破解本地化悖论：让非设计员工秒级生成合规内容", 
    subtitle: "通过解码品牌基因并建立 AI 设计规则库，让一线非设计人员也能秒级生成合规素材，化解了总部集中管控与地方敏捷需求之间的矛盾。", 
    updatedAt: "2026-02-15", 
    readTime: "6", 
    tags: ["地产", "内容战略"], 
    clientIntro: "全球化地产集团，拥有30多个品牌。", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cSOO.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "痛点：规模化与品牌统一性的内在矛盾" },
      { type: 'p', content: "对于一个在全球运营数十个子品牌的大型集团而言，品牌一致性是其核心资产。然而，一线营销团队常常有紧急的、高度本地化的内容需求（例如，针对特定节假日的促销海报、社区活动的邀请函）。如果求助于总部设计中心，往往需要排队数周，错过最佳营销时机；如果允许一线团队自行创作，则极易导致品牌视觉语言的走样和滥用。这是“集中管控”与“敏捷需求”之间的一个根本性冲突。" },
      { type: 'h2', content: "解决方案：将品牌基因解码为 AI 可执行的规则" },
      { type: 'p', content: "我们的核心思路是，将品牌规范从一本厚厚的、静态的VI手册，转变为一个动态的、可被 AI 理解和执行的规则系统。我们与集团的品牌中心合作，将核心的品牌资产（如Logo、IP形象）解构为可灵活组合的组件库，并建立了 AI 可理解的色彩、字体、构图和留白规则库。" },
      { type: 'p', content: "在新的工作流程中，任何一名员工，无论是否具备设计背景，都可以登录内容平台，选择场景或主题（如“婚礼季促销”），输入关键信息。AI 会在严格遵守品牌规则的前提下，实时生成多种合规的设计方案供其选择。这里的关键在于，AI 不是在进行无约束的随机创作，而是在一个由品牌专家定义的精密框架内，进行无限次的、合规的组合与创新。" },
      { type: 'quote', content: "内容生产从‘天/周’级进入‘分钟’级。非设计员工成为更懂场景的设计师。" },
      { type: 'metrics', items: [{ label: '生产耗时', value: '<1 min', sub: '单次设计' }, { label: '品牌合规', value: '100%', sub: '规则控制' }] }
    ] 
  },
  { 
    slug: 'luxury-retail-compliance', 
    type: 'case', 
    title: "解放注意力：提升关键业务节点的决策判断力", 
    subtitle: "部署 AI 视觉智能体接管社交媒体内容的初筛工作，通过结构化的审美与合规规则，将营销团队的注意力从繁琐审核中解放出来。", 
    updatedAt: "2026-02-10", 
    readTime: "6", 
    tags: ["奢侈品", "合规风控"], 
    clientIntro: "某奢侈品品牌营销团队。", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1caQm.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "痛点：宝贵的人类注意力被浪费在低价值任务上" },
      { type: 'p', content: "该奢侈品牌的市场专员，每天需要花费大量时间人工浏览数百篇由门店导购或合作KOC在社交平台发布的内容。他们的任务有两个：找出不符合品牌规范的违规贴文，并发现具有潜力的优质用户生成内容（UGC）以便进行二次推广。这项工作极其繁琐、重复性高，且容易出错。这导致团队没有足够的时间和精力去思考真正的推广策略，而是将宝贵的注意力耗费在了无尽的、低价值的细节审查中。" },
      { type: 'h2', content: "解决方案：将主观判断转化为 AI 可执行的决策 Agent" },
      { type: 'p', content: "我们认为，许多看似主观的“判断”工作，其底层逻辑是可以被结构化的。我们与品牌方合作，将“何为优质”、“何为违规”这些模糊的标准，转化为一个结构化的规则体系。例如，我们将违规定义为包含竞品Logo、不雅词汇、价格信息泄露等具体项；将优质定义为符合品牌色调偏好、构图有美感、文案情感积极等。我们部署的智能决策 Agent 7x24小时不间断地扫描相关社交媒体帖子，进行毫秒级的多维度判断。它不仅能自动过滤掉99%的违规内容，更能基于“优质”规则，自动推荐出最具传播潜力的内容，并附上推荐理由，供营销团队决策是否进行官方“加热”。" },
      { type: 'quote', content: "AI 完成 100% 的初筛与推荐，人类专家处理 1% 的复杂边界案例并优化规则。" },
      { type: 'h2', content: "价值重塑：让人类专家回归战略高地" },
      { type: 'p', content: "实施该方案后，市场团队的工作重心发生了根本性转变。他们不再是内容的“警察”，而是内容的“策展人”和“策略师”。他们可以将时间用于分析AI推荐的优质内容背后的趋势，策划更有创意的营销活动，以及处理那些需要复杂人类情感理解的边界案例，从而不断优化AI的判断规则。这是一种更高效、也更具创造性的人机协作模式。" },
      { type: 'metrics', items: [{ label: '初筛覆盖', value: '100%' }, { label: '人工介入', value: '1%', sub: '仅处理边界' }] }
    ] 
  }
];

const reportsCnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'middle-layer-trap', 
    type: 'report', 
    title: "为什么只买 AI 软件是不够的？", 
    subtitle: "单纯购买 AI 软件无法直接产生商业价值。企业需要跨越工具与结果之间的“中间层”，即通过专业服务重塑组织流程与人员认知。", 
    updatedAt: "2026-01-10", 
    readTime: "8", 
    tags: ["战略", "行业洞察"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1c0yH.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "普遍的误区：将 AI 视为 IT 采购项目" },
      { type: 'p', content: "在与超过 200 家不同行业的企业级用户合作中，我们观察到一个普遍现象：许多公司将引入 AI 视为又一次的软件采购。他们期待通过购买一套先进的工具，就能自动解决业务问题。然而，现实是，绝大多数这样的项目最终都未能产生预期的商业价值，AI 工具最终沦为少数技术人员的“玩具”，无法融入核心业务流程。" },
      { type: 'h2', content: "工具公司的“三个错位”" },
      { type: 'p', content: "问题的根源在于，单纯的软件工具公司与企业客户之间存在着三个根本性的错位：" },
      { type: 'p', content: "1. **时间错位**：AI 技术和产品以周或月为单位快速迭代，而企业的组织架构、工作流程和员工习惯的改变则需要以季度或年为单位。这种速度差导致工具的能力与组织的吸收能力严重脱节。" },
      { type: 'p', content: "2. **视角错位**：工具公司天然地从“功能视角”出发，强调自己的软件能做什么。而企业客户真正关心的是“结果视角”，即如何解决我的特定业务问题，如何提升收入或降低成本。" },
      { type: 'p', content: "3. **责任错位**：工具公司的责任边界是“交付可用的软件”，而企业客户的期望是“交付可衡量的业务结果”。这两者之间存在着巨大的鸿沟。" },
      { type: 'h2', content: "缺失的“中间层”：专业服务与变革管理" },
      { type: 'p', content: "如果只停留在工具层，企业实际上是在绕开最难但也最关键的那一层：专业服务与变革管理。这一“中间层”包括了如何将 AI 的能力与企业具体的业务战略相结合，如何重新设计与之配套的工作流程，以及如何培训员工、调整组织架构以适应新的工作方式。它回答的是“如何用”和“如何管”的问题，而不仅仅是“用什么”。" },
      { type: 'quote', content: "工具解决的是‘能力缺口’，而专业服务解决的是‘认知与组织缺口’。" },
      { type: 'p', content: "因此，成功的 AI 转型，本质上是一个由 CEO 驱动的、伤筋动骨的变革管理项目，而不是一个可以完全外包给 IT 部门的采购项目。它需要的是一个能够深入理解业务、提供全栈式服务的长期合作伙伴，而不仅仅是一个软件供应商。" }
    ] 
  }
];

const methodsCnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'ai-full-stack-model', 
    type: 'methodology', 
    title: "什么是 AI Full Stack 公司？", 
    subtitle: "未来的 AI Native 企业需要具备“全栈”能力：不仅拥有底层的工具基础设施，更具备重写业务剧本的能力以及与之匹配的新型组织架构。", 
    updatedAt: "2026-01-20", 
    readTime: "7", 
    tags: ["框架模型", "组织设计"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1jNtN.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "超越工具：AI 时代的价值创造新范式" },
      { type: 'p', content: "在 AI 时代，企业间的竞争不再仅仅是产品或服务的竞争，而是“工作方式”的竞争。能够更高效地利用 AI 进行决策、创新和运营的企业将获得决定性的优势。然而，要实现这一点，企业需要一套从工具、方法到组织的一体化能力。我们将其定义为“AI Full Stack” (AI 全栈) 能力。" },
      { type: 'h2', content: "Full Stack 的三层结构" },
      { type: 'p', content: "我们认为，一个真正的 AI Native 公司，无论是服务方还是应用方，都必须在这三个层面都建立起核心能力：" },
      { type: 'p', content: "**第一层是工具层（Tools）**：这是基础。它包括了对底层大模型的理解与封装能力、高质量的行业数据资产，以及将 AI 能力产品化为稳定、易用的工作流应用。这一层确保了 AI 能力的可及性与可靠性。" },
      { type: 'p', content: "**第二层是业务层（Business）**：这是价值实现的核心。它要求我们具备用 AI 的视角去重新审视和设计核心业务流程的能力。例如，如何将传统的内容生产线改造为自动化的“内容供应链”？如何将基于经验的产品研发，转变为由“信号洞察”驱动的敏捷创新引擎？这一层决定了 AI 能否真正产生商业价值。" },
      { type: 'p', content: "**第三层是人和组织层（People & Org）**：这是变革成功的保障。它关注的是如何帮助 CEO 和核心团队回答在 AI 时代最根本的问题：“我的团队的最高价值到底是什么？”这涉及到重新定义人和 AI 的分工边界，设计新的协作机制，以及培训员工具备设计和优化 AI 工作流的“新能力”。" },
      { type: 'h3', content: "不仅是咨询，更是交付可运行的业务闭环" },
      { type: 'p', content: "如果没有后两层，第一层的工具大概率只会停留在一句口号：“我们做了一个很厉害的系统，欢迎来用。” AI Full Stack 意味着我们不只交付软件或战略报告，而是交付一套能够真正在客户业务中跑起来、持续产生价值、并能自我进化的业务闭环。这是一种更深度、更负责任的合作模式。" }
    ] 
  },
  { 
    slug: 'change-management', 
    type: 'methodology', 
    title: "变革管理：AI 转型的本质是 Change Management", 
    subtitle: "AI 转型的核心在于组织变革。我们需要为核心团队制定“新宪法”，通过黑客松共创业务场景，并重新定义中层管理者的角色与价值。", 
    updatedAt: "2026-01-25", 
    readTime: "6", 
    tags: ["变革管理", "领导力"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1j3eA.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "为什么技术 внедрение (implementation) 往往会失败？" },
      { type: 'p', content: "生意不会因为购买了新软件就自己变好，组织也不会因为部署了 AI 系统就自动变得更智能。AI 转型的最大障碍往往不是技术本身，而是组织惯性、员工的旧有习惯以及僵化的管理流程。因此，我们坚信，任何成功的 AI 项目，本质上都是一个精心设计的变革管理（Change Management）项目。" },
      { type: 'h2', content: "系统性地推动组织变革三部曲" },
      { type: 'p', content: "我们通过系统性的三件事来确保 AI 不仅被“引入”，更能被真正地“融入”到组织中：" },
      { type: 'p', content: "**第一，为 CEO 和核心团队制定一部“组织新宪法”**。我们通过高层工作坊，帮助领导团队就“人和 AI 的分工边界”、“AI 决策的授权范围”以及“新的绩效考核标准”等核心问题达成共识，并形成清晰的、可传达的变革纲领。" },
      { type: 'p', content: "**第二，为业务团队举办“AI 共创营与黑客松”**。我们反对空泛的理论培训。我们直接将业务团队带入围绕真实业务目标的实战中。工具当场学习，流程当场设计，最小化可行产品（MVP）第二天就在真实环境中上线试错。这种“干中学”的方式能最快地打破员工的恐惧感，建立使用 AI 的信心和能力。" },
      { type: 'p', content: "**第三，为未来的中层与骨干进行“角色重置”**。在新的工作方式下，许多中层管理者传统的“上传下达”和“协调资源”的价值被削弱。我们为他们设计了新的角色定位——“AI 工作流设计师”或“人机协作教练”，并提供相应的培训，帮助他们从流程的执行者，转变为流程的设计者和优化者。" },
      { type: 'quote', content: "在这个意义上，培训不再是补技能，而是换身份。" }
    ] 
  }
];

const announcementsCnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'consulting-launch-offer', 
    type: 'announcement', 
    title: "Tezign AI Consulting 服务体系发布", 
    subtitle: "我们提供从业务诊断、工作流设计到组织进化的全链路服务，帮助企业在现有组织内挖掘 AI 的最高商业价值，实现可持续增长。", 
    updatedAt: "2026-03-05", 
    readTime: "3", 
    tags: ["服务发布", "产品体系"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1j1f4.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "直面挑战：将 AI 从“可能性”变为“生产力”" },
      { type: 'p', content: "当前，几乎所有企业都认识到 AI 的巨大潜力，但如何将这种潜力转化为实实在在的、可衡量的业务增长，是每一位决策者面临的共同挑战。为了应对这一挑战，Tezign 正式发布 AI-native 咨询服务体系，致力于成为企业在 AI 转型道路上最值得信赖的合作伙伴。" },
      { type: 'h2', content: "我们的服务模块：一个完整的转型路线图" },
      { type: 'p', content: "**1. AI 业务诊断与组织体检（2-4周）**：我们首先会对您的业务进行深度访谈和数据分析，精准定位在现有组织和技术基础下，AI 可实现的最高商业价值和最易切入的干预点。最终交付物是一份清晰的“策略一页纸”和一份详细的“AI 干预点图谱”，明确转型的优先级和预期 ROI。" },
      { type: 'p', content: "**2. AI 工作流设计与部署（4-6周）**：我们将诊断阶段的洞察，转化为一个或多个可运行的、定制化的 AI 工作流系统。无论是“竞品追踪 Agent”、“内容合规 Agent”还是“市场机会识别 Agent”，我们都会为您完成专属的训练、部署和与现有系统的集成，确保它能解决您最核心的痛点。" },
      { type: 'p', content: "**3. AI 组织进化与增长（按需持续）**：我们提供订阅制的持续服务，确保 AI 系统能够根据业务变化和技术进步不断进化。这包括定期的模型调优、新场景的共创建模，以及对您团队的持续赋能培训，确保 AI 能力能够真正沉淀为企业的长期资产。" }
    ] 
  }
];

// --- EN Data (Translated from Source) ---

const casesEnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'manufacturing-innovation-radar', 
    type: 'case', 
    title: "Building an 'Innovation Radar': Shortening Concept Iteration to Hours", 
    subtitle: "Helping a leading manufacturer build a systematic information radar with AI Agents to tackle information overload in early-stage R&D, successfully cutting the concept iteration cycle from weeks to hours.", 
    updatedAt: "2026-03-01", 
    readTime: "8", 
    tags: ["Manufacturing", "Product Innovation"], 
    clientIntro: "A leading manufacturing company.", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cUN0.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "The 'Day One' Challenge: Drowning in Data, Starving for Insight" },
      { type: 'p', content: "A major issue many companies face is that the 'first step' of product innovation is the hardest. The company's product managers were overwhelmed daily by hundreds of industry reports, competitor updates, and technical papers. The traditional innovation process began with an exhausting information war—teams spent weeks collecting, reading, and trying to piece together trends from fragments. The result was often depleted inspiration, unclear direction, and missed market windows." },
      { type: 'p', content: "This passive, labor-intensive approach not only consumed the team's valuable energy but also led directly to high opportunity costs. The inability to quickly validate early concepts meant multiple projects were pursued in parallel, many of which ultimately failed due to market mismatch, resulting in millions of dollars in sunk costs and causing the company to lose its first-mover advantage in a competitive market." },
      { type: 'h2', content: "Solution: From Manual Search to an AI-Powered 'Innovation Radar'" },
      { type: 'p', content: "Instead of just providing an information tool, we redefined the front-end of the innovation process. Our solution was designed in two core parts: a 24/7 AI signal intelligence engine and a weekly human-AI collaborative product concept workshop." },
      { type: 'h3', content: "Step 1: Building the 24/7 Signal Intelligence Engine" },
      { type: 'p', content: "Working with the client's core R&D team, we first defined four key observation dimensions: cutting-edge technologies (academic papers, patent filings), competitor dynamics (product launches, price adjustments), user feedback (social media, forums), and supply chain signals (new materials, cost fluctuations). We then deployed and trained dedicated AI Agents to automatically scrape, clean, and cross-validate information in these areas, transforming raw data into structured insights." },
      { type: 'h3', content: "Step 2: Human-AI Collaborative Concept Workshops" },
      { type: 'p', content: "Each week, the AI automatically generated an 'Opportunity Report' based on its analysis, highlighting high-potential signals in summary form (e.g., 'The application of AVC encoding models in automotive cockpit entertainment systems is trending up'). We guided the product team in deep discussions around these highly concentrated signals, with the AI present as a 'participant,' generating concept sketches, user stories, and preliminary feasibility analyses in real-time based on the team's discussion." },
      { type: 'quote', content: "The traditional process is 'manual search + brainstorming,' whereas the AI workflow should be 'systematic information scanning + human-machine co-creation of product concepts.'" },
      { type: 'h2', content: "Outcomes: Speed, Savings, and a New R&D Culture" },
      { type: 'p', content: "By fully automating the tedious work of information gathering and organization, the product team's energy was freed up to focus on the most valuable creative and strategic thinking. The AI provided not scattered data, but pre-processed 'fuel' for thought, enabling high-quality product concepts to emerge from every weekly workshop. Ultimately, the company not only achieved significant financial returns but, more importantly, established a new, agile R&D culture driven by data and AI." },
      { type: 'metrics', items: [{ label: 'R&D Time Saved', value: '70%' }, { label: 'Savings/Category', value: 'Millions', sub: 'R&D Expenses' }, { label: 'Cycle Time', value: 'Hours', sub: 'From Weeks' }] }
    ] 
  },
  { 
    slug: 'pharma-knowledge-management', 
    type: 'case', 
    title: "Unlocking 'Dark Knowledge': Making Knowledge Bases Conversational", 
    subtitle: "By building an enterprise knowledge graph, we transformed a static document repository into a conversational 'corporate brain,' helping analysts improve cross-system decision response times from days to minutes.", 
    updatedAt: "2026-02-28", 
    readTime: "7", 
    tags: ["Pharma", "Knowledge Management"], 
    clientIntro: "A leading pharmaceutical enterprise.", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cZUF.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Pain Point: Buried Treasure of Immense Value" },
      { type: 'p', content: "Every company hides 'Dark Knowledge,' scattered across project reports, expert experience, meeting minutes, and email communications. This pharmaceutical company's market analysts spent over 600 hours each month manually extracting, cleaning, and integrating data from a dozen separate systems to analyze sales data from hundreds of pharmacy chains nationwide. New hires took months to get up to speed, and the departure of key experts meant the permanent loss of invaluable experience." },
      { type: 'h2', content: "Solution: Building an Enterprise AI Knowledge Graph" },
      { type: 'p', content: "Traditional knowledge management is like 'building a warehouse'; it archives files, but the connections between knowledge are severed, creating a hard-to-navigate maze. Our AI knowledge management consulting logic is to 'build a brain.' We began with a comprehensive audit of knowledge assets to identify high-value domains and designed a 'Knowledge Operations' process to ensure new knowledge is continuously captured and updated." },
      { type: 'p', content: "The key step was not simply importing data, but redesigning the flow of knowledge. Using Natural Language Processing (NLP), we automatically extracted entities (like drug names, ingredients, promotional activities) and their relationships from unstructured documents to build a dynamic knowledge graph. Now, a manager can simply ask in natural language, 'Compare the correlation between promotional spending and sales for Product A in our key accounts in Southern and Eastern China over the past two years, and analyze the response strategies of major competitors.' Within a minute, the system generates an analytical report with visualizations and source citations." },
      { type: 'h2', content: "Impact: From 'Data Archaeology' to 'Real-Time Decision-Making'" },
      { type: 'p', content: "This transformation shifted the role of analysts from 'data archaeologists' to true 'strategic advisors.' They no longer waste time on repetitive data extraction and can instead leverage the deep insights provided by AI to offer more forward-looking recommendations to business units. Corporate decisions are no longer solely reliant on the personal experience of a few experts but are built upon a foundation of traceable, verifiable collective intelligence." },
      { type: 'metrics', items: [{ label: 'Hours Saved', value: '600h+', sub: 'Per Month' }, { label: 'Response Time', value: 'Minutes', sub: 'From Days' }] }
    ] 
  },
  { 
    slug: 'fmcg-consumer-insight', 
    type: 'case', 
    title: "Beyond Static Surveys: Real-time Insights via Synthetic Users", 
    subtitle: "Replacing traditional surveys with synthetic user technology and using Proactive Agents for massive concurrent interviews to provide real-time, dynamic market insights for a billion-dollar product line.", 
    updatedAt: "2026-02-25", 
    readTime: "9", 
    tags: ["FMCG", "Consumer Insights"], 
    clientIntro: "A top consumer goods company.", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1crep.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Pain Point: Expensive and Outdated 'Static Photos'" },
      { type: 'p', content: "Traditional consumer research is like taking a static photo of a constantly moving market: it's costly, takes months to complete, and its conclusions are entirely dependent on a limited sample. By the time the final report is ready, consumer preferences may have already shifted. The dilemma for the company was that it was making decisions about the future of a multi-billion dollar product based on a blurry and potentially outdated snapshot, a process fraught with risk and uncertainty." },
      { type: 'h2', content: "Solution: From 'Photo' to 'Live Stream' for Real-Time Market Interaction" },
      { type: 'p', content: "The core of our methodology was to shift from 'static insight' to 'dynamic sensing.' Using Atypica™ technology, we combined the client's first-party data with public market data to generate thousands of multi-dimensional virtual users highly consistent with real consumer profiles. These 'synthetic users' were endowed not just with demographic characteristics, but also with values, consumption habits, and motivation models." },
      { type: 'p', content: "Our AI consulting team first conducted a 'Business Problem Deconstruction,' breaking down the client's vague business objectives (e.g., 'increase purchase intent among Gen Z') into a series of core questions that could be explored by AI, covering dimensions like user motivation, usage scenarios, and willingness to pay. Then, Proactive Agents took over the research execution, simulating professional interviewers to conduct deep, open-ended conversations simultaneously with hundreds of synthetic and real user samples. The agents could even ask follow-up questions in real-time based on responses to dig for deeper reasons. Our analysts then distilled the structured data from the AI to interpret core strategic opportunities, such as 'health upgrade, not functional replacement,' and provided specific product feature and marketing recommendations." },
      { type: 'h2', content: "Business Value: Finding Certainty in Uncertainty" },
      { type: 'p', content: "This 'live stream' model allows the company to conduct large-scale, low-cost rapid experimentation at the product concept stage. They can test dozens of different product concepts or marketing messages in a matter of days and get immediate feedback, enabling them to discard unpromising ideas early and focus resources on the most likely winners. This not only dramatically reduces the cost of innovation but, more importantly, provides the company with a powerful capability to find certainty in a fast-changing market." },
      { type: 'metrics', items: [{ label: 'Cost Reduction', value: '60%' }, { label: 'Launch Speed', value: '350%', sub: 'Improvement' }, { label: 'Insight Speed', value: '100x' }] }
    ] 
  },
  { 
    slug: 'alcohol-channel-growth', 
    type: 'case', 
    title: "Reshaping Sales Networks: The 'Create-Distribute-Reward' Loop", 
    subtitle: "Deploying an AI Content Engine for thousands of distributors to establish an automated 'create-distribute-reward' loop, effectively solving issues of inconsistent content quality and management difficulties.", 
    updatedAt: "2026-02-20", 
    readTime: "8", 
    tags: ["Alcohol", "Channel Growth"], 
    clientIntro: "A leading liquor enterprise.", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cju9.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Pain Point: 'Spray and Pray' in Channel Digitization" },
      { type: 'p', content: "In the new media era, the social influence of terminal stores and Key Opinion Consumers (KOCs) is crucial for brands. However, this brand faced a major challenge: its thousands of distributors nationwide generally lacked content creation skills, leading to a coarse and inconsistent brand image on social media. Headquarters was unable to effectively manage and incentivize these scattered outputs. The traditional model of 'issuing tasks + broadcasting in WeChat groups' was highly inefficient, and content performance data was a black hole due to platform fragmentation." },
      { type: 'h2', content: "Solution: An Intelligent Workflow Driven by Content" },
      { type: 'p', content: "We didn't just provide a content production tool; we designed an end-to-end intelligent workflow that fully integrated 'creation-distribution-incentivization.' First, we translated the brand's marketing objectives (e.g., high-end banquet scenarios, traditional holiday gifting) into AI-understandable creative briefs and visual dimensions (like image quality, cultural elements, copy style)." },
      { type: 'p', content: "In the new workflow, headquarters releases marketing tasks on the platform. Distributors can access an AI creation assistant with one click, enter simple ideas or keywords, and generate high-quality images, text, or short video scripts that align with the brand's tone in seconds. Before publication, the content undergoes a preliminary compliance check by AI to ensure brand information is accurate. After publishing, the platform uses APIs to track propagation data in real-time and automatically allocates rewards to distributors based on preset incentive rules (like impressions and engagement rate). In this process, the AI simultaneously plays the roles of creative producer, quality gatekeeper, and performance analyst." },
      { type: 'h2', content: "Business Impact: Transforming the Channel Network into a Brand Amplifier" },
      { type: 'p', content: "This solution not only solved the efficiency and quality problems of content production but, more importantly, it transformed the vast and loose network of distributors into an efficient, controllable, data-driven brand content amplifier. For the first time, headquarters could clearly see the content marketing performance of each region and every store, and use this as a basis to optimize channel strategies and resource allocation. This was not just an IT system upgrade but a fundamental reshaping of the traditional channel management model." },
      { type: 'metrics', items: [{ label: 'Efficiency', value: '+75%' }, { label: 'Exposure', value: '50M+', sub: 'Deep Binding' }] }
    ] 
  },
  { 
    slug: 'real-estate-localization', 
    type: 'case', 
    title: "Solving the Localization Paradox: Instant Compliant Content Generation", 
    subtitle: "By decoding brand DNA and establishing an AI design rule library, non-design frontline staff can now generate compliant materials in seconds, resolving the conflict between central control and local agile needs.", 
    updatedAt: "2026-02-15", 
    readTime: "6", 
    tags: ["Real Estate", "Content Strategy"], 
    clientIntro: "Global Real Estate Group.", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1cSOO.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Pain Point: The Inherent Conflict Between Scale and Brand Consistency" },
      { type: 'p', content: "For a large corporation operating dozens of sub-brands globally, brand consistency is a core asset. However, frontline marketing teams often have urgent, highly localized content needs (e.g., promotional posters for specific holidays, invitations for community events). Requesting support from the headquarters' design center often meant waiting weeks, missing the optimal marketing window. Allowing frontline teams to create their own content, on the other hand, easily led to dilution and misuse of the brand's visual language. This represents a fundamental conflict between 'centralized control' and 'agile needs.'" },
      { type: 'h2', content: "Solution: Decoding Brand DNA into AI-Executable Rules" },
      { type: 'p', content: "Our core idea was to transform the brand guidelines from a thick, static VI manual into a dynamic, AI-understandable and executable rule system. We collaborated with the group's brand center to deconstruct core brand assets (like logos and IP images) into a flexible component library. We then established an AI-readable rulebook for colors, fonts, composition, and white space." },
      { type: 'p', content: "In the new workflow, any employee, regardless of their design background, can log into the content platform, select a scenario or theme (like 'Wedding Season Promotion'), and input key information. The AI then generates multiple compliant design options in real-time, strictly adhering to the brand rules. The key here is that the AI is not performing unconstrained random creation, but rather infinite, compliant combinations and innovations within a precise framework defined by brand experts." },
      { type: 'quote', content: "Content production has moved from a 'day/week' level to a 'minute' level. Non-design employees have become designers who better understand the context." },
      { type: 'metrics', items: [{ label: 'Production Time', value: '<1 min' }, { label: 'Compliance', value: '100%' }] }
    ] 
  },
  { 
    slug: 'luxury-retail-compliance', 
    type: 'case', 
    title: "Freeing Attention: Enhancing Judgment at Key Decision Nodes", 
    subtitle: "Deploying AI Visual Agents to take over the initial screening of social media content, freeing up the marketing team's attention from tedious reviews through structured aesthetic and compliance rules.", 
    updatedAt: "2026-02-10", 
    readTime: "6", 
    tags: ["Luxury", "Compliance"], 
    clientIntro: "Luxury Brand Marketing Team.", 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1caQm.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Pain Point: Wasting Valuable Human Attention on Low-Value Tasks" },
      { type: 'p', content: "Marketing specialists at this luxury brand were spending a significant portion of their day manually reviewing hundreds of social media posts from store associates or partner KOCs. Their mission was twofold: identify non-compliant posts that violated brand guidelines and discover high-potential user-generated content (UGC) for further promotion. This work was extremely tedious, repetitive, and prone to error. It left the team with insufficient time and energy to focus on true promotion strategy, instead of getting bogged down in endless, low-value detail checking." },
      { type: 'h2', content: "Solution: Transforming Subjective Judgment into an AI-Executable Decision Agent" },
      { type: 'p', content: "We believe that the underlying logic of many seemingly subjective 'judgment' tasks can be structured. We worked with the brand to convert vague standards of 'what is high-quality' and 'what is a violation' into a structured rule system. For example, we defined violations as containing competitor logos, inappropriate language, or price information leaks, and defined quality by adherence to brand color palettes, aesthetic composition, and positive sentiment in the copy. The deployed Intelligent Decision Agent scans relevant social media posts 24/7, making multi-dimensional judgments in milliseconds. It not only filters out 99% of non-compliant content but also automatically recommends posts with the most viral potential based on the 'quality' rules, complete with a rationale for the recommendation, for the marketing team to decide whether to officially 'boost' it." },
      { type: 'quote', content: "AI completes 100% of the initial screening and recommendations; human experts handle the 1% of complex edge cases and optimize the rules." },
      { type: 'h2', content: "Value Reshaped: Returning Human Experts to Strategic Heights" },
      { type: 'p', content: "After implementing this solution, the marketing team's focus fundamentally shifted. They were no longer content 'police' but content 'curators' and 'strategists.' They could now use their time to analyze the trends behind the AI-recommended high-quality content, plan more creative marketing campaigns, and handle the edge cases that require complex human emotional understanding, thereby continuously refining the AI's judgment rules. This is a more efficient and more creative model of human-machine collaboration." },
      { type: 'metrics', items: [{ label: 'Screening Coverage', value: '100%' }, { label: 'Human Intervention', value: '1%', sub: 'Edge Cases Only' }] }
    ] 
  }
];

const reportsEnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'middle-layer-trap', 
    type: 'report', 
    title: "Why Buying AI Software Is Not Enough", 
    subtitle: "Simply purchasing AI software doesn't directly generate business value. Companies need to bridge the 'middle layer' between tools and results by reshaping organizational processes and personnel cognition through professional services.", 
    updatedAt: "2026-01-10", 
    readTime: "8", 
    tags: ["Strategy", "Industry Insights"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1c0yH.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "The Common Misconception: Treating AI as an IT Procurement Project" },
      { type: 'p', content: "In our collaboration with over 200 enterprise clients across various industries, we've observed a common phenomenon: many companies treat the introduction of AI as just another software purchase. They expect that buying an advanced tool will automatically solve their business problems. The reality, however, is that the vast majority of such projects fail to produce the expected business value, and the AI tools end up as 'toys' for a few technicians, never integrated into core business processes." },
      { type: 'h2', content: "The 'Three Misalignments' of Tool Companies" },
      { type: 'p', content: "The root of the problem lies in three fundamental misalignments between pure-play software tool companies and their enterprise clients:" },
      { type: 'p', content: "1. **Time Misalignment**: AI technology and products iterate rapidly, on a weekly or monthly basis, while changes in a company's organizational structure, workflows, and employee habits take quarters or even years. This speed difference creates a severe disconnect between the tool's capabilities and the organization's ability to absorb them." },
      { type: 'p', content: "2. **Perspective Misalignment**: Tool companies naturally start from a 'feature perspective,' emphasizing what their software can do. Enterprise clients, however, are concerned with a 'results perspective'—how to solve their specific business problems, increase revenue, or reduce costs." },
      { type: 'p', content: "3. **Responsibility Misalignment**: The responsibility of a tool company ends at 'delivering functional software.' The enterprise client's expectation is 'delivering measurable business results.' A huge gap exists between these two." },
      { type: 'h2', content: "The Missing 'Middle Layer': Professional Services and Change Management" },
      { type: 'p', content: "By focusing only on the tool layer, companies are effectively bypassing the most difficult but also the most critical layer: professional services and change management. This 'middle layer' includes how to align AI capabilities with the company's specific business strategy, how to redesign supporting workflows, and how to train employees and adjust the organizational structure to adapt to new ways of working. It answers the questions of 'how to use' and 'how to manage,' not just 'what to use.'" },
      { type: 'quote', content: "Tools solve the 'capability gap,' while professional services solve the 'cognition and organizational gap.'" },
      { type: 'p', content: "Therefore, a successful AI transformation is essentially a CEO-driven, deeply disruptive change management project, not a procurement task that can be fully outsourced to the IT department. It requires a long-term partner who can deeply understand the business and provide full-stack services, not just a software vendor." }
    ] 
  }
];

const methodsEnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'ai-full-stack-model', 
    type: 'methodology', 
    title: "What is an AI Full Stack Company?", 
    subtitle: "Future AI-native enterprises need a 'full-stack' capability: not only the underlying tool infrastructure but also the ability to rewrite business playbooks and the new organizational structures to match.", 
    updatedAt: "2026-01-20", 
    readTime: "7", 
    tags: ["Framework", "Organizational Design"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1jNtN.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Beyond Tools: A New Paradigm for Value Creation in the AI Era" },
      { type: 'p', content: "In the AI era, competition between companies is no longer just about products or services, but about 'ways of working.' Companies that can more effectively use AI for decision-making, innovation, and operations will gain a decisive advantage. To achieve this, however, companies need an integrated set of capabilities spanning tools, methods, and organization. We define this as the 'AI Full Stack' capability." },
      { type: 'h2', content: "The Three Layers of the Full Stack" },
      { type: 'p', content: "We believe that a truly AI-native company, whether a service provider or an adopter, must build core competencies in these three layers:" },
      { type: 'p', content: "**Layer 1: Tools**: This is the foundation. It includes the ability to understand and encapsulate underlying large models, high-quality industry data assets, and the productization of AI capabilities into stable, user-friendly workflow applications. This layer ensures the accessibility and reliability of AI capabilities." },
      { type: 'p', content: "**Layer 2: Business**: This is the core of value realization. It requires the ability to re-examine and redesign core business processes from an AI perspective. For example, how to transform a traditional content production line into an automated 'content supply chain'? How to shift from experience-based product development to an agile innovation engine driven by 'signal intelligence'? This layer determines whether AI can genuinely generate business value." },
      { type: 'p', content: "**Layer 3: People & Org**: This is the guarantee of successful transformation. It focuses on helping CEOs and core teams answer the most fundamental question of the AI era: 'What is the highest value of my team?' This involves redefining the division of labor between humans and AI, designing new collaboration mechanisms, and training employees with the 'new skills' to design and optimize AI workflows." },
      { type: 'h3', content: "Not Just Consulting, but Delivering an Operable Business Loop" },
      { type: 'p', content: "Without the latter two layers, the first layer of tools will most likely remain a mere slogan: 'We've built a powerful system, feel free to use it.' AI Full Stack means we deliver not just software or strategic reports, but a complete business loop that can actually run, continuously generate value, and self-evolve within the client's business. This is a deeper, more responsible partnership model." }
    ] 
  },
  { 
    slug: 'change-management', 
    type: 'methodology', 
    title: "Change Management: The Essence of AI Transformation", 
    subtitle: "The core of AI transformation lies in organizational change. We need to create a 'new constitution' for the core team, co-create business scenarios through hackathons, and redefine the role and value of middle managers.", 
    updatedAt: "2026-01-25", 
    readTime: "6", 
    tags: ["Change Management", "Leadership"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1j3eA.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Why Technology Implementations Often Fail" },
      { type: 'p', content: "Business doesn't get better on its own just because new software is purchased, and an organization doesn't automatically become smarter just because an AI system is deployed. The biggest obstacles to AI transformation are often not the technology itself, but organizational inertia, employees' old habits, and rigid management processes. Therefore, we firmly believe that any successful AI project is, in essence, a well-designed change management project." },
      { type: 'h2', content: "A Three-Part Systematic Approach to Driving Organizational Change" },
      { type: 'p', content: "We use three systematic actions to ensure that AI is not just 'introduced' but truly 'integrated' into the organization:" },
      { type: 'p', content: "**First, we establish a 'New Organizational Constitution' for the CEO and core team.** Through high-level workshops, we help the leadership team reach a consensus on core issues such as 'the division of labor between humans and AI,' 'the scope of AI's decision-making authority,' and 'new performance evaluation criteria,' forming a clear and communicable framework for change." },
      { type: 'p', content: "**Second, we organize 'AI Co-creation Camps and Hackathons' for business teams.** We oppose vague theoretical training. We directly immerse business teams in practical sessions focused on real business goals. Tools are learned on the spot, workflows are designed in the session, and a Minimum Viable Product (MVP) is launched for trial in a real environment the next day. This 'learning by doing' approach is the fastest way to break down employees' fears and build their confidence and ability to use AI." },
      { type: 'p', content: "**Third, we conduct a 'Role Reset' for future middle managers and key personnel.** In the new way of working, the traditional value of many middle managers in 'relaying information' and 'coordinating resources' is diminished. We design new role positionings for them—such as 'AI Workflow Designer' or 'Human-Machine Collaboration Coach'—and provide corresponding training to help them transition from being executors of processes to designers and optimizers of processes." },
      { type: 'quote', content: "In this sense, training is no longer about acquiring skills, but about changing identities." }
    ] 
  }
];

const announcementsEnData: Omit<LibraryItem, 'audioData'>[] = [
  { 
    slug: 'consulting-launch-offer', 
    type: 'announcement', 
    title: "Tezign AI Consulting Services Launched", 
    subtitle: "We offer end-to-end services from business diagnostics and workflow design to organizational evolution, helping companies unlock the highest commercial value of AI and achieve sustainable growth.", 
    updatedAt: "2026-03-05", 
    readTime: "3", 
    tags: ["Service Launch"], 
    coverImageUrl: "https://i.imgs.ovh/2025/12/29/C1j1f4.jpeg", 
    contentBlocks: [
      { type: 'h2', content: "Facing the Challenge: Turning AI from 'Possibility' to 'Productivity'" },
      { type: 'p', content: "Today, nearly every enterprise recognizes the immense potential of AI. However, translating that potential into tangible, measurable business growth is a common challenge facing every decision-maker. To address this challenge, Tezign is officially launching its AI-native consulting services, committed to becoming the most trusted partner for enterprises on their AI transformation journey." },
      { type: 'h2', content: "Our Service Modules: A Complete Transformation Roadmap" },
      { type: 'p', content: "**1. AI Business Diagnosis & Organizational Health Check (2-4 weeks)**: We begin with in-depth interviews and data analysis of your business to pinpoint the highest commercial value and easiest entry points for AI intervention within your current organization and technology stack. The final deliverables are a clear 'One-Page Strategy' and a detailed 'AI Intervention Map,' clarifying transformation priorities and expected ROI." },
      { type: 'p', content: "**2. AI Workflow Design & Deployment (4-6 weeks)**: We translate the insights from the diagnosis phase into one or more operational, customized AI workflow systems. Whether it's a 'Competitor Tracking Agent,' a 'Content Compliance Agent,' or a 'Market Opportunity Identification Agent,' we will handle the custom training, deployment, and integration with your existing systems to ensure it solves your most critical pain points." },
      { type: 'p', content: "**3. AI Organizational Evolution & Growth (Ongoing, as needed)**: We offer a subscription-based continuous service to ensure that the AI system evolves with business changes and technological advancements. This includes regular model tuning, co-creation of models for new scenarios, and continuous empowerment training for your team, ensuring that AI capabilities truly become a long-term asset for the enterprise." }
    ] 
  }
];

const casesCn = casesCnData.map(addAudioData);
const reportsCn = reportsCnData.map(addAudioData);
const methodsCn = methodsCnData.map(addAudioData);
const announcementsCn = announcementsCnData.map(addAudioData);

const casesEn = casesEnData.map(addAudioData);
const reportsEn = reportsEnData.map(addAudioData);
const methodsEn = methodsEnData.map(addAudioData);
const announcementsEn = announcementsEnData.map(addAudioData);

// --- Search Logic (Unchanged) ---
const allCnItems = [...casesCn, ...reportsCn, ...methodsCn, ...announcementsCn];
const allEnItems = [...casesEn, ...reportsEn, ...methodsEn, ...announcementsEn];

const bilingualIndex = allCnItems.map(cnItem => {
  const enItem = allEnItems.find(i => i.slug === cnItem.slug);
  const enTitle = enItem?.title.toLowerCase() || '';
  const enSubtitle = enItem?.subtitle.toLowerCase() || '';
  const enTags = enItem?.tags.join(' ').toLowerCase() || '';
  
  const cnTitle = cnItem.title.toLowerCase();
  const cnSubtitle = cnItem.subtitle.toLowerCase();
  const cnTags = cnItem.tags.join(' ').toLowerCase();

  return {
    slug: cnItem.slug,
    cnTitle,
    enTitle,
    fullText: `${cnTitle} ${cnSubtitle} ${cnTags} ${enTitle} ${enSubtitle} ${enTags}`
  };
});

export const searchLibrary = (query: string): string[] => {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  const scored = bilingualIndex.map(item => {
    let score = 0;
    if (item.cnTitle.includes(q) || item.enTitle.includes(q)) {
      score += 10;
    }
    if (item.fullText.includes(q)) {
      score += 1;
    }
    return { slug: item.slug, score };
  });

  return scored
    .filter(i => i.score > 0)
    .sort((a, b) => b.score - a.score)
    .map(i => i.slug);
};

export const getData = (lang: 'en' | 'cn') => {
  if (lang === 'cn') {
    return {
      cases: casesCn,
      reports: reportsCn,
      methodologies: methodsCn,
      announcements: announcementsCn,
      all: [...casesCn, ...reportsCn, ...methodsCn, ...announcementsCn]
    };
  } else {
    return {
      cases: casesEn,
      reports: reportsEn,
      methodologies: methodsEn,
      announcements: announcementsEn,
      all: [...casesEn, ...reportsEn, ...methodsEn, ...announcementsEn]
    };
  }
};